"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useQuote } from "@/components/quote-context";
import { CheckIcon, ChevronIcon, TrashIcon } from "@/components/icons";

type QuoteForm = { institution: string; cnpj: string; institutionType: string; city: string; state: string; name: string; role: string; phone: string; whatsapp: string; email: string; message: string; consent: boolean; website: string };
const initial: QuoteForm = { institution: "", cnpj: "", institutionType: "", city: "", state: "", name: "", role: "", phone: "", whatsapp: "", email: "", message: "", consent: false, website: "" };
const steps = ["Produtos", "Instituição", "Contato", "Revisão"];

export function QuoteFlow() {
  const { items, removeItem, updateItem, clear } = useQuote();
  const [step, setStep] = useState(1);
  const [form, setForm] = useState(initial);
  const [error, setError] = useState("");
  const [sending, setSending] = useState(false);
  const [protocol, setProtocol] = useState("");
  const stepHeading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { if (step > 1) stepHeading.current?.focus(); }, [step]);
  function update<K extends keyof QuoteForm>(key: K, value: QuoteForm[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function advance(next: number) { setError(""); setStep(next); const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches; window.scrollTo({ top: 300, behavior: reducedMotion ? "auto" : "smooth" }); }
  function institutionValid() { if (form.institution.trim().length < 2 || !form.institutionType || form.city.trim().length < 2 || !form.state) { setError("Preencha instituição, tipo, cidade e estado."); return false; } return true; }
  function contactValid() { if (form.name.trim().length < 2 || form.phone.trim().length < 8 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) { setError("Preencha nome, telefone e e-mail válidos."); return false; } return true; }
  async function submit(event: FormEvent) { event.preventDefault(); if (!form.consent) { setError("É necessário aceitar a política de privacidade."); return; } setError(""); setSending(true); try { const response = await fetch("/api/contato", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, type: "orcamento", organization: form.institution, context: form.message || "Solicitação de orçamento com produtos selecionados.", items: items.map(({ slug, name, quantity, notes }) => ({ slug, name, quantity, notes })) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Não foi possível validar a solicitação."); setProtocol(`LAB-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}-${crypto.randomUUID().slice(0, 6).toUpperCase()}`); clear(); setStep(5); } catch (caught) { setError(caught instanceof Error ? caught.message : "Ocorreu um erro de validação."); } finally { setSending(false); } }
  if (step === 5) return <div className="shell py-24"><div className="mx-auto max-w-2xl rounded-[2rem] border border-slate-200 bg-white p-8 text-center shadow-sm md:p-14"><span className="mx-auto grid size-16 place-items-center rounded-full bg-emerald-50 text-teal-700"><CheckIcon className="size-8" /></span><p className="eyebrow mt-7">Validação concluída</p><h1 ref={stepHeading} tabIndex={-1} className="display mt-4 text-4xl">Solicitação validada</h1><p className="mt-5 leading-7 text-slate-600">Este ambiente demonstrativo não persiste nem encaminha a solicitação. O protocolo abaixo é gerado apenas no navegador e não comprova recebimento pela Labtech.</p><div className="mx-auto mt-7 max-w-sm rounded-2xl bg-slate-100 p-5"><p className="text-xs uppercase tracking-widest text-slate-500">Protocolo demonstrativo</p><p className="mt-2 font-mono text-lg font-bold">{protocol}</p></div><Link href="/" className="button button-primary mt-8">Voltar ao início</Link></div></div>;
  return <div className="shell py-14"><div className="mx-auto max-w-5xl"><ol className="mb-10 grid grid-cols-4 gap-2" aria-label={`Etapa ${step} de 4`}>{steps.map((label, index) => <li key={label} aria-current={step === index + 1 ? "step" : undefined} className={`flex items-center text-xs font-bold ${step >= index + 1 ? "text-teal-700" : "text-slate-400"}`}><span className={`grid size-8 shrink-0 place-items-center rounded-full ${step >= index + 1 ? "bg-teal-700 text-white" : "bg-slate-200"}`}>{index + 1}</span><span className="ml-2 hidden sm:inline">{label}</span>{index < 3 && <ChevronIcon className="ml-auto size-4 text-slate-300" />}</li>)}</ol><form onSubmit={submit} aria-busy={sending} className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-10">
    {step === 1 && <section><p className="eyebrow">Etapa 01 · Produtos</p><h1 className="display mt-3 text-4xl">Produtos do orçamento</h1>{items.length ? <ul className="mt-8 space-y-5">{items.map((item) => <li className="rounded-2xl border border-slate-200 p-5" key={item.slug}><div className="flex items-start justify-between gap-4"><div><p className="font-semibold">{item.name}</p><label className="mt-3 block text-sm font-semibold">Quantidade<input type="number" min="1" max="999" className="input mt-1 w-28" value={item.quantity} onChange={(event) => updateItem(item.slug, { quantity: Number(event.target.value) || 1 })} /></label></div><button type="button" onClick={() => removeItem(item.slug)} className="icon-button" aria-label={`Remover ${item.name}`}><TrashIcon className="size-4" /></button></div><label className="mt-4 block text-sm font-semibold">Observações do item<textarea className="input mt-2 min-h-24 font-normal" maxLength={500} value={item.notes} onChange={(event) => updateItem(item.slug, { notes: event.target.value })} /></label></li>)}</ul> : <div className="mt-8 rounded-2xl border border-dashed border-slate-300 p-8 text-center"><p className="font-semibold">Nenhum produto selecionado</p><Link href="/catalogo" className="mt-4 inline-block font-bold text-teal-700">Escolher no catálogo</Link></div>}<div className="mt-8 flex justify-end"><button type="button" onClick={() => advance(2)} className="button button-primary">Continuar <ChevronIcon className="size-4" /></button></div></section>}
    {step === 2 && <section><p className="eyebrow">Etapa 02 · Instituição</p><h1 className="display mt-3 text-4xl">Dados da instituição</h1><div className="mt-8 grid gap-5 sm:grid-cols-2"><Field label="Instituição" required value={form.institution} onChange={(value) => update("institution", value)} autoComplete="organization" /><Field label="CNPJ" value={form.cnpj} onChange={(value) => update("cnpj", value)} placeholder="Opcional" /><label className="text-sm font-semibold">Tipo de instituição <span className="text-red-700">*</span><select className="input mt-2 font-normal" value={form.institutionType} onChange={(event) => update("institutionType", event.target.value)}><option value="">Selecione</option><option>Laboratório</option><option>Hospital ou clínica</option><option>Distribuidor</option><option>Instituição de ensino ou pesquisa</option><option>Indústria</option><option>Outro</option></select></label><Field label="Cidade" required value={form.city} onChange={(value) => update("city", value)} autoComplete="address-level2" /><label className="text-sm font-semibold">Estado <span className="text-red-700">*</span><select className="input mt-2 font-normal" value={form.state} onChange={(event) => update("state", event.target.value)} autoComplete="address-level1"><option value="">Selecione</option>{["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"].map((state) => <option key={state}>{state}</option>)}</select></label></div>{error && <ErrorMessage text={error} />}<Navigation back={() => advance(1)} next={() => institutionValid() && advance(3)} /></section>}
    {step === 3 && <section><p className="eyebrow">Etapa 03 · Contato</p><h1 className="display mt-3 text-4xl">Dados para contato</h1><div className="mt-8 grid gap-5 sm:grid-cols-2"><Field label="Nome" required value={form.name} onChange={(value) => update("name", value)} autoComplete="name" /><Field label="Cargo" value={form.role} onChange={(value) => update("role", value)} autoComplete="organization-title" /><Field label="Telefone" required type="tel" value={form.phone} onChange={(value) => update("phone", value)} autoComplete="tel" /><Field label="WhatsApp" type="tel" value={form.whatsapp} onChange={(value) => update("whatsapp", value)} placeholder="Opcional" /><Field label="E-mail" required type="email" value={form.email} onChange={(value) => update("email", value)} autoComplete="email" wide /><label className="text-sm font-semibold sm:col-span-2">Mensagem<textarea className="input mt-2 font-normal" maxLength={2000} value={form.message} onChange={(event) => update("message", event.target.value)} placeholder="Inclua contexto adicional para a solicitação." /></label></div>{error && <ErrorMessage text={error} />}<Navigation back={() => advance(2)} next={() => contactValid() && advance(4)} /></section>}
    {step === 4 && <section><p className="eyebrow">Etapa 04 · Revisão</p><h1 className="display mt-3 text-4xl">Revise antes de validar</h1><div className="mt-8 grid gap-6 md:grid-cols-2"><Review title="Instituição" edit={() => advance(2)} lines={[form.institution, `${form.institutionType} · ${form.city}/${form.state}`, form.cnpj && `CNPJ: ${form.cnpj}`]} /><Review title="Contato" edit={() => advance(3)} lines={[form.name, form.role, form.phone, form.whatsapp && `WhatsApp: ${form.whatsapp}`, form.email]} /></div><div className="mt-6 rounded-2xl border border-slate-200 p-5"><h2 className="font-semibold">Produtos</h2>{items.length ? <ul className="mt-3 space-y-3">{items.map((item) => <li key={item.slug} className="text-sm"><strong>{item.quantity}× {item.name}</strong>{item.notes && <p className="mt-1 text-slate-500">{item.notes}</p>}</li>)}</ul> : <p className="mt-2 text-sm text-slate-500">Solicitação sem produto selecionado.</p>}</div><label className="absolute -left-[10000px]" aria-hidden="true">Página pessoal<input tabIndex={-1} autoComplete="off" value={form.website} onChange={(event) => update("website", event.target.value)} /></label><label className="mt-6 flex items-start gap-3 text-sm leading-6 text-slate-600"><input type="checkbox" className="mt-1 size-4 accent-teal-700" required checked={form.consent} onChange={(event) => update("consent", event.target.checked)} />Li a <Link href="/politica-de-privacidade" className="font-bold text-teal-700">política de privacidade</Link> e concordo com a validação dos dados.</label><p className="mt-4 text-xs text-slate-500">Este ambiente não persiste nem encaminha solicitações.</p>{error && <ErrorMessage text={error} />}<div className="mt-8 flex justify-between gap-3"><button type="button" onClick={() => advance(3)} className="button button-outline">Voltar</button><button disabled={sending} type="submit" className="button button-primary disabled:opacity-50">{sending ? "Validando..." : "Validar solicitação"}</button></div></section>}
  </form></div></div>;
}

function Field({ label, required, type = "text", value, onChange, placeholder, autoComplete, wide }: { label: string; required?: boolean; type?: string; value: string; onChange: (value: string) => void; placeholder?: string; autoComplete?: string; wide?: boolean }) { return <label className={`text-sm font-semibold ${wide ? "sm:col-span-2" : ""}`}>{label} {required && <span className="text-red-700">*</span>}<input type={type} className="input mt-2 font-normal" required={required} maxLength={160} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} autoComplete={autoComplete} /></label>; }
function Navigation({ back, next }: { back: () => void; next: () => void }) { return <div className="mt-8 flex justify-between gap-3"><button type="button" onClick={back} className="button button-outline">Voltar</button><button type="button" onClick={next} className="button button-primary">Continuar <ChevronIcon className="size-4" /></button></div>; }
function ErrorMessage({ text }: { text: string }) { return <p className="mt-5 text-sm text-red-700" role="alert">{text}</p>; }
function Review({ title, lines, edit }: { title: string; lines: (string | false)[]; edit: () => void }) { return <div className="rounded-2xl border border-slate-200 p-5"><div className="flex justify-between"><h2 className="font-semibold">{title}</h2><button type="button" onClick={edit} className="text-sm font-bold text-teal-700">Editar</button></div>{lines.filter(Boolean).map((line) => <p className="mt-2 text-sm text-slate-600" key={String(line)}>{line}</p>)}</div>; }
